import type { Issue } from './types.js';

export const KNOWN_PROJECT_IDS = ['acme-payments', 'legacy-billing'] as const;

const T = '2026-08-14T09:12:00.000Z';

export const SEED_ISSUES: Issue[] = [
  // acme-payments
  {
    id: 'iss-001',
    projectId: 'acme-payments',
    filePath: 'src/auth/login.ts',
    line: 3,
    type: 'VULNERABILITY',
    severity: 'BLOCKER',
    status: 'OPEN',
    rule: 'S6418',
    message: 'Hard-coded credential: a live API token is committed to source.',
    author: null,
    createdAt: T,
    updatedAt: T,
  },
  {
    id: 'iss-002',
    projectId: 'acme-payments',
    filePath: 'src/auth/login.ts',
    line: 7,
    type: 'VULNERABILITY',
    severity: 'CRITICAL',
    status: 'CONFIRMED',
    rule: 'S3649',
    message: 'SQL query is built from user-controlled input; use a parameterized query.',
    author: null,
    createdAt: T,
    updatedAt: T,
  },
  {
    id: 'iss-003',
    projectId: 'acme-payments',
    filePath: 'src/auth/login.ts',
    line: 12,
    type: 'QUALITY_GATE_VIOLATION',
    severity: 'MAJOR',
    status: 'OPEN',
    rule: 'S1440',
    message: 'Use the strict equality operator === instead of ==.',
    author: null,
    createdAt: T,
    updatedAt: T,
  },
  {
    id: 'iss-004',
    projectId: 'acme-payments',
    filePath: 'src/auth/login.ts',
    line: 12,
    type: 'COMMENT',
    severity: null,
    status: 'OPEN',
    rule: null,
    message: 'Comparing against a plaintext password column. Is this hashed anywhere?',
    author: 'marie',
    createdAt: T,
    updatedAt: T,
  },
  {
    id: 'iss-005',
    projectId: 'acme-payments',
    filePath: 'src/auth/login.ts',
    line: 18,
    type: 'VULNERABILITY',
    severity: 'MAJOR',
    status: 'FALSE_POSITIVE',
    rule: 'S2076',
    message: 'Authentication bypass helper is exported as part of the public API.',
    author: null,
    createdAt: T,
    updatedAt: T,
  },
  {
    id: 'iss-006',
    projectId: 'acme-payments',
    filePath: 'src/payments/charge.ts',
    line: 8,
    type: 'VULNERABILITY',
    severity: 'BLOCKER',
    status: 'OPEN',
    rule: 'S5145',
    message: 'Log entry contains full cardholder data.',
    author: null,
    createdAt: T,
    updatedAt: T,
  },
  {
    id: 'iss-007',
    projectId: 'acme-payments',
    filePath: 'src/payments/charge.ts',
    line: 12,
    type: 'QUALITY_GATE_VIOLATION',
    severity: 'MINOR',
    status: 'OPEN',
    rule: 'S109',
    message: 'Magic numbers 0.029 and 30 should be named constants.',
    author: null,
    createdAt: T,
    updatedAt: T,
  },
  {
    id: 'iss-008',
    projectId: 'acme-payments',
    filePath: 'src/payments/charge.ts',
    line: 12,
    type: 'COMMENT',
    severity: null,
    status: 'OPEN',
    rule: null,
    message: 'This fee formula is duplicated in legacy-billing invoice.py. Extract it.',
    author: 'tom',
    createdAt: T,
    updatedAt: T,
  },
  {
    id: 'iss-009',
    projectId: 'acme-payments',
    filePath: 'src/payments/charge.ts',
    line: 16,
    type: 'COMMENT',
    severity: null,
    status: 'OPEN',
    rule: null,
    message: 'MAX_AMOUNT has been unused since the v3 rewrite.',
    author: 'marie',
    createdAt: T,
    updatedAt: T,
  },
  // legacy-billing
  {
    id: 'iss-010',
    projectId: 'legacy-billing',
    filePath: 'billing/invoice.py',
    line: 7,
    type: 'VULNERABILITY',
    severity: 'BLOCKER',
    status: 'OPEN',
    rule: 'S5135',
    message: 'Deserializing untrusted data with pickle allows remote code execution.',
    author: null,
    createdAt: T,
    updatedAt: T,
  },
  {
    id: 'iss-011',
    projectId: 'legacy-billing',
    filePath: 'billing/invoice.py',
    line: 10,
    type: 'VULNERABILITY',
    severity: 'MAJOR',
    status: 'RESOLVED',
    rule: 'S5443',
    message: 'Predictable file name in the shared /tmp directory.',
    author: null,
    createdAt: T,
    updatedAt: T,
  },
  {
    id: 'iss-012',
    projectId: 'legacy-billing',
    filePath: 'billing/invoice.py',
    line: 11,
    type: 'VULNERABILITY',
    severity: 'CRITICAL',
    status: 'OPEN',
    rule: 'S4721',
    message: 'OS command is built by string concatenation.',
    author: null,
    createdAt: T,
    updatedAt: T,
  },
  {
    id: 'iss-013',
    projectId: 'legacy-billing',
    filePath: 'billing/invoice.py',
    line: 11,
    type: 'COMMENT',
    severity: null,
    status: 'OPEN',
    rule: null,
    message: 'Shelling out to wkhtmltopdf is the last blocker for the container migration.',
    author: 'sofia',
    createdAt: T,
    updatedAt: T,
  },
  {
    id: 'iss-014',
    projectId: 'legacy-billing',
    filePath: 'billing/invoice.py',
    line: 15,
    type: 'QUALITY_GATE_VIOLATION',
    severity: 'MINOR',
    status: 'OPEN',
    rule: 'S109',
    message: 'Magic number 30 should be a named constant.',
    author: null,
    createdAt: T,
    updatedAt: T,
  },
  {
    id: 'iss-015',
    projectId: 'legacy-billing',
    filePath: 'billing/db.py',
    line: 4,
    type: 'VULNERABILITY',
    severity: 'BLOCKER',
    status: 'OPEN',
    rule: 'S2068',
    message: 'Hard-coded database password.',
    author: null,
    createdAt: T,
    updatedAt: T,
  },
  {
    id: 'iss-016',
    projectId: 'legacy-billing',
    filePath: 'billing/db.py',
    line: 11,
    type: 'VULNERABILITY',
    severity: 'CRITICAL',
    status: 'OPEN',
    rule: 'S3649',
    message: 'SQL query is built from user-controlled input.',
    author: null,
    createdAt: T,
    updatedAt: T,
  },
  {
    id: 'iss-017',
    projectId: 'legacy-billing',
    filePath: 'billing/db.py',
    line: 11,
    type: 'COMMENT',
    severity: null,
    status: 'OPEN',
    rule: null,
    message: 'Same injection as acme-payments login.ts. Fix both together.',
    author: 'tom',
    createdAt: T,
    updatedAt: T,
  },
  {
    id: 'iss-018',
    projectId: 'legacy-billing',
    filePath: 'requirements.txt',
    line: 1,
    type: 'VULNERABILITY',
    severity: 'MAJOR',
    status: 'OPEN',
    rule: 'S4823',
    message: 'requests 2.19.1 has known published CVEs; upgrade to >= 2.32.',
    author: null,
    createdAt: T,
    updatedAt: T,
  },
  {
    id: 'iss-019',
    projectId: 'legacy-billing',
    filePath: 'requirements.txt',
    line: 3,
    type: 'VULNERABILITY',
    severity: 'CRITICAL',
    status: 'OPEN',
    rule: 'S5135',
    message: 'pyyaml 3.13 permits arbitrary code execution through yaml.load.',
    author: null,
    createdAt: T,
    updatedAt: T,
  },
];
